title: Chaozhe's Blog
description: > # this means to ignore newlines until "baseurl:"
  Chaozhe's Personal Blog with thoughts and journal of my life.
permalink: /blog/:year/:month/:day/:title/
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Chaozhe He # add your name
author-img: George_Patton.jpg # add your photo
about-author: To improve is to change. To perfect is to change often # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: hchaozhe # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: chaozhehe # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 6
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
