name:               "Chaozhe He"
description:        "To improve is to change, to be perfect is to change often"

url:                "hchaozhe.github.io"
author:             "ChaozheHe"
email:              "hchaozhe@umich.edu"
gravatar_hash:      "f66118e374b1450f61780521b9a95fec"
twitter:            "Robert.Chaozhe.He"
email:              "hchaozhe@umich.edu"
github:             "hchaozhe"
pinterest:          "chaozhehe"
linkedin:           "chaozhe-he-04606017"
facebook:           "chaozhe.he"

# disqus_shortname:   "thinker3197"

# the background picture
background:         "BackgroundForBlog1"

paginate:           10
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

plugins: 
  - jekyll-paginate