title: Chaozhe's Blog   # your title
author: Chaozhe He # your name
description: To improve is to change, to be perfect is to change often # your description
avatar: /images/George_Patton.jpg # change avatar

# Build Settings
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/page:num/"
plugins: 
  - jekyll-paginate

# Comments
# disqus:
#   shortname: xxxx-xxxxx-xxx   # your disqus shortname

# Google Analytics
# google_analytics: xx-xxxxxxxx-1  # your google analytics

theme: jekyll-theme-leap-day